// <auto-generated />
namespace App.Migrations

open System
open AzureApp.DbModel
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<ApplicationDbContext>)>]
[<Migration("20210706235420_Initial")>]
type Initial() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "Rooms"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "int"
                    ).Annotation("SqlServer:Identity", "1, 1")
                name =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(max)"
                    )
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_Rooms", (fun x -> (x.Id) :> obj)) |> ignore
                ) 
        ) |> ignore

        migrationBuilder.CreateTable(
            name = "Users"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "int"
                    ).Annotation("SqlServer:Identity", "1, 1")
                name =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(max)"
                    )
                bio =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(max)"
                    )
                RoomId =
                    table.Column<int>(
                        nullable = true
                        ,``type`` = "int"
                    )
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_Users", (fun x -> (x.Id) :> obj)) |> ignore
                    table.ForeignKey(
                        name = "FK_Users_Rooms_RoomId",
                        column = (fun x -> (x.RoomId) :> obj)
                        ,principalTable = "Rooms"
                        ,principalColumn = "Id"
                        ,onDelete = ReferentialAction.Restrict
                        ) |> ignore

                ) 
        ) |> ignore

        migrationBuilder.CreateIndex(
            name = "IX_Users_RoomId"
            ,table = "Users"
            ,column = "RoomId"
            ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "Users"
            ) |> ignore

        migrationBuilder.DropTable(
            name = "Rooms"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder

            .UseIdentityColumns().HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("ProductVersion", "5.0.7")
            |> ignore

        modelBuilder.Entity("AzureApp.DbModel.Room", (fun b ->

            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                .UseIdentityColumn() |> ignore
            b.Property<string>("name")
                .HasColumnType("nvarchar(max)") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("Rooms") |> ignore

        )) |> ignore

        modelBuilder.Entity("AzureApp.DbModel.User", (fun b ->

            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                .UseIdentityColumn() |> ignore
            b.Property<Nullable<int>>("RoomId")
                .HasColumnType("int") |> ignore
            b.Property<string>("bio")
                .HasColumnType("nvarchar(max)") |> ignore
            b.Property<string>("name")
                .HasColumnType("nvarchar(max)") |> ignore

            b.HasKey("Id") |> ignore


            b.HasIndex("RoomId") |> ignore

            b.ToTable("Users") |> ignore

        )) |> ignore

        modelBuilder.Entity("AzureApp.DbModel.User", (fun b ->
            b.HasOne("AzureApp.DbModel.Room",null)
                .WithMany("users")
                .HasForeignKey("RoomId") |> ignore
        )) |> ignore

